server:
  port: 50600
  max-http-header-size: 10000000
  tomcat:
    remoteip:
      host-header:

logging:
  config: classpath:log4j2.xml

spring:
  redis:
    password:

  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/chain_storage?characterEncoding=utf8"
    username: root
    password: MyNewPass5ABC

  jpa:
    hibernate:
      ddl-auto: update
      dialect: "org.hibernate.dialect.MySQL5InnoDBDialect"

settings:
  MaxCidLen: 256
  MaxNodeExtLen: 4096
  MaxUserExtLen: 4096
  MaxFileExtLen: 4096
  MaxNodeCanAddFile: 1000000
  MaxNodeCanDeleteFile: 1000000
  Replica: 1
  UserInitSpace: 5368709120

resolverAddress: "0x678c7f5af8a48a06f4e4076220e4ad9a013b20f7"

chain:
  groupId: 1