server:
  port: 50600
  max-http-header-size: 10000000

logging:
  config: classpath:log4j2.xml

spring:
  redis:
    password:

  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/chain_storage?characterEncoding=utf8"
    username: root
    password: MyNewPass5ABC

  jpa:
    hibernate:
      ddl-auto: update
      dialect: "org.hibernate.dialect.MySQL5InnoDBDialect"

settings:
  MaxCidLen: 256
  MaxNodeExtLen: 4096
  MaxUserExtLen: 4096
  MaxFileExtLen: 4096
  MaxNodeCanAddFile: 1000000
  MaxNodeCanDeleteFile: 1000000
  Replica: 1
  UserInitSpace: 5368709120

resolverAddress: "0x0102223f21eecb2c9a22c6d027cc9fc37cb6235a"

chain:
  groupId: 1