server:
  port: 50600

logging:
  config: classpath:log4j2.xml

settings:
  MaxCidLen: 256
  MaxNodeExtLen: 4096
  MaxUserExtLen: 4096
  MaxFileExtLen: 4096
  MaxNodeCanAddFile: 1000000
  MaxNodeCanDeleteFile: 1000000
  Replica: 1
  UserInitSpace: 5368709120


GroupId: 1
passwd: "123456"
resolverAddress: "0x678c7f5af8a48a06f4e4076220e4ad9a013b20f7"