server:
  port: 50600

logging:
  config: classpath:log4j2.xml

settings:
  MaxCidLen: 256
  MaxNodeExtLen: 40960
  MaxUserExtLen: 40960
  MaxFileExtLen: 40960
  MaxNodeCanAddFile: 100
  MaxNodeCanDeleteFile: 100
  Replica: 2
  UserInitSpace: 300000000000


GroupId: 1
passwd: "123456"
resolverAddress: "0xa6bf6919c30bdc5ccec23e1b24d5e4952c3c3b62"